config/routes.rb
Rails.application.routes.draw do

  resources 'surveys'
  resources 'attempts'
  match '(errors)/:status', to: 'errors#error_404', constraints: {status: /\d{3}/}, via: :all
  get '/passwordverification',to: 'surveys#quiz_confirm_password'
  post 'verifyPass',to: 'surveys#quiz_verfication'
  mount Ckeditor::Engine => '/ckeditor'
  resources :notes
  get 'tags/:tag', to: 'home#index', as: :tag
 get '/result/:id' => 'surveys#result'
  resources :questions

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :comments
  resources :answers
  resources :questions

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  get '/likenotification',to: 'notification#likeindex'
  get 'home/index'
  get '/sear',to: 'questions#index'
  devise_for :users, :controllers => { sessions: "sessions", registrations: "registrations",:omniauth_callbacks => "omniauth_callbacks" }
  devise_scope :user do
    authenticated :user do
      root 'home#indexmain', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  resources :users,only: [:show,:edit,:update]
  get '/users_list'=>'home#users_list'
  get '/tags_list'=>'home#tags_list'
 
  resources :questions do
    post 'like',   to: 'socializations#like'
    post 'follow', to: 'socializations#followQuestion'
  end

  resources :answers do
    post 'like',   to: 'socializations#likeAnswer'
  end
  resources :trends do
    post 'follow', to: 'socializations#followTrend'
  end
  resources :users do
    post 'follow', to: 'socializations#followUser'
  end

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
    validates :title ,presence: true,length:{maximum:140,
    too_long: "%{count} characters is the maximum allowed" }

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

# TO SHOW ALL NOTES
  def index
    @notes=Note.where(:user_id => current_user.id).order(updated_at: :desc)
  end

# TO SHOW A NOTE
  def show
  end

# FOR NEW NOTE
  def new
    @note = Note.new
  end

# TO EDIT A NOTE
  def edit
  end

# TO CREATE ALL NOTE
  def create
    @note = Note.new(note_params)
  @note.user_id = current_user.id

    respond_to do |format|
      if @note.save
        format.html { redirect_to request.referrer, notice: 'Note was successfully created.' }
        format.js{}
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

# TO UPDATE A NOTE
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

# TO DELETE ALL NOTE
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title,:content,:user_id)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>

  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="card z-depth-4 center" style="border-radius: 10px;">
  <div class="green darken-3 z-depth-4" style="padding-bottom:20px;">
    <br>
    <span class="card-title white-text">Edit Note</span>
    <br>
  </div>
  <form>
    <div class="col s12" style="padding:40px;">
<br>
<br>
      <div class="input-field">
        <%= f.text_field :title ,class:"validate"%>
        <label for="note_title" data-error="wrong" data-success="right">Title</label>
      </div>
       <div class="input-field">
        <%= f.text_area :content ,class:'validate materialize-textarea'%>
        <label for="notecontent_" data-error="wrong" data-success="right">Content</label>
      </div>
    </div>
    <br>
    <div class="action" style="padding:40px;">
      <%= f.submit "Save" , class:"waves-effect waves-light btn green darken-3"%>
      <%= link_to 'Back', notes_path , class:"waves-effect waves-light btn green darken-3"%>
    </div>
  </form>
</div>
<% end %>

<script type="text/javascript">
  $('.tooltipped').tooltip({delay: 50});
</script>

app/views/notes/_note.html.erb
<style type="text/css">





  .carall.wrapper {
    font-family:sans;
    margin: 0px;
    margin-top: 20px;
  }

  /* Note styles */
  .carall.wrapper .note-wrap {
    width: 235px;
    min-height: 235px;
    padding: 8px;
    padding-top: 15px;
    margin: 0 22px 44px 22px;
    position: relative;
    font-size: 24px;
    vertical-align: top;
    display: inline-block;
    font-family: Englebert, Arial;
    color: #4b453c;
    background: #F7E999;
    line-height: 34px;
    text-align: center;
    box-shadow: 0 4px 5px rgba(0, 0, 0, 0.2);

  }
  .carall.wrapper .note-wrap:before {
    display: block;
    content: "";
    background: rgba(227, 200, 114, 0.4);
    width: 130px;
    height: 28px;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0.2);
    border-radius: 6px/18px 0;
    position: absolute;
    top: -13px;
    left: 50px;
    -webkit-transform: rotate(-2deg);
    -moz-transform: rotate(-2deg);
    -o-transform: rotate(-2deg);
    -ms-transform: rotate(-2deg);
    transform: rotate(-2deg);
  }

  .carall.wrapper .note-blue {
    background: #b9dcf4;

    -webkit-transform: rotate(2deg);
    -moz-transform: rotate(2deg);
    -o-transform: rotate(2deg);
    -ms-transform: rotate(2deg);
    transform: rotate(2deg);
  }

  .carall.wrapper .note-yellow {
   background: #F7E999;
   -webkit-transform: rotate(-2deg);
   -moz-transform: rotate(-2deg);
   -o-transform: rotate(-2deg);
   -ms-transform: rotate(-2deg);
   transform: rotate(-2deg);
   border-radius: 12px;
 }
 .carall.wrapper .note-yellow .fixed-action-btn{
  right: 2px;
  bottom: 2px;

}
aside.note-wrap.note-yellow div.fixed-action-btn.horizontal ul li a i.material-icons.btn-floating{
  font-size: 25px;
}
div.carall.wrapper aside.note-wrap.note-yellow h5{
font-size: 17px;
font-weight: 800;
font-family: Fresca,sans-serif;
margin: 0px;
margin-top: 10px;
}
div.carall.wrapper aside.note-wrap.note-yellow p#notetitle{
text-transform: uppercase;
margin: 0px;
font-weight: bold;
font-family: 'Lato, sans-serif';
}
div.carall.wrapper aside.note-wrap.note-yellow p#notecontent{

margin: 0px;
margin-top: 4px; 
overflow-y: scroll;
height: 160px;
}
</style>
<div class="col s12 m6">

 <div class="carall wrapper">

  <aside class="note-wrap note-yellow">
   <h5><%= time_ago_in_words(note.updated_at) unless note.created_at.blank? %> ago</h5>
   <p id="notetitle"><%= note.title %></p>
   <p id="notecontent"><%= note.content %></p>
   <br>
   <div class="fixed-action-btn horizontal">
    <a class="btn-floating btn-large waves-effect waves-light red z-depth-4">
      <i class="large material-icons">menu</i>
    </a>
    <ul>
     <!--  <li><a href="#modaladdnote" class="btn-floating green"><i class="material-icons">mode_edit</i></a></li> -->

      <li><%= link_to ('<i class="material-icons btn-floating blue tooltipped" data-position="bottom" data-delay="50" data-tooltip="Delete">delete</i>').html_safe, note, method: :delete, data: {confirm: "Are you sure?"}%></li>
     <li><%= link_to ('<i class=" material-icons btn-floating yellow darken-1 tooltipped" data-position="bottom" data-delay="50" data-tooltip="Edit">create</i>').html_safe, edit_note_path(note)%></li>
        
      </ul>
    </div>
  </aside>
</div>


</div>

app/views/notes/create.js.erb
$('#notes').prepend("<%= escape_javascript (render 'home/', note: @note) %>");
$('#note_title').val("");
$('#note_content').val("");

app/views/notes/edit.html.erb
<%= render 'form' %>
<!-- <%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %> -->

app/views/notes/index.html.erb
   <div class="row">
    <% @notes.each do |note| %>
    <%= render 'note' , note: note %>
      
    <% end %>
    </div>
  
<br>


   
        
            

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Note:</strong>
  <%= @note.title %>
  <%= @note.content %>
</p>
<br>
<p>
  <strong>User:</strong>
  <%= link_to @note.user.name,user_path(@note.user.id) %>
 
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>

<%= link_to 'New Note', new_note_path %>