config/routes.rb
Rails.application.routes.draw do

  resources 'surveys'
  resources 'attempts'
  match '(errors)/:status', to: 'errors#error_404', constraints: {status: /\d{3}/}, via: :all
  get '/passwordverification',to: 'surveys#quiz_confirm_password'
  post 'verifyPass',to: 'surveys#quiz_verfication'
  mount Ckeditor::Engine => '/ckeditor'
  resources :notes
  get 'tags/:tag', to: 'home#index', as: :tag
 get '/result/:id' => 'surveys#result'
  resources :questions

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :comments
  resources :answers
  resources :questions

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  get '/likenotification',to: 'notification#likeindex'
  get 'home/index'
  get '/sear',to: 'questions#index'
  devise_for :users, :controllers => { sessions: "sessions", registrations: "registrations",:omniauth_callbacks => "omniauth_callbacks" }
  devise_scope :user do
    authenticated :user do
      root 'home#indexmain', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  resources :users,only: [:show,:edit,:update]
  get '/users_list'=>'home#users_list'
  get '/tags_list'=>'home#tags_list'
 
  resources :questions do
    post 'like',   to: 'socializations#like'
    post 'follow', to: 'socializations#followQuestion'
  end

  resources :answers do
    post 'like',   to: 'socializations#likeAnswer'
  end
  resources :trends do
    post 'follow', to: 'socializations#followTrend'
  end
  resources :users do
    post 'follow', to: 'socializations#followUser'
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: [:index]

# FOR ALL USERS PAGE
  def users_list
    respond_to do |format|
      format.html {
        if params[:search]
          @users=User.where(name: params[:search]).paginate(:per_page => 20, :page => params[:page])
        else
          @users=User.all.order(:name).paginate(:per_page => 10, :page => params[:page])
        end
      }
      format.js {}
    end
  end

# FOR ALL QUESTIONS ACCORDING TO TAGS
  def index
    @questagfeed = []
    if params[:question_id]
      @question=Question.find(params[:id])
      @question.tag_list.each do |tag|
        @questagfeed += Question.tagged_with(tag)
      end
    elsif params[:tag]
      @trendtagusers = []
      @tre=Trend.where(name: params[:tag]).first
      @trendtagusers += @tre.followers(User)
    else
      @tftags=Question.tag_counts_on(:tags).order('count desc').limit(5)
      @tftags.each do |tag|
        @questagfeed += Question.tagged_with(tag)
      end
    end
    respond_to do |format|
      format.html {
        @question = Question.new
        if params[:tag]
          @trend=Trend.where(name: params[:tag]).first
          @feed = Question.tagged_with(params[:tag]).paginate(:per_page => 20, :page => params[:page])
        elsif params[:search]
          v=User.search(params[:search]).paginate(:per_page=>20, :page=> params[:page])
          if v== nil
            @feed=Question.search(params[:search]).paginate(:per_page => 20, :page => params[:page])
          else
            @users=User.search(params[:search]).paginate(:per_page => 20, :page => params[:page])
            @feed=Question.search(params[:search]).paginate(:per_page => 20, :page => params[:page])
          end
        else
          @feed=current_user.feed.paginate(:per_page => 7, :page => params[:page])
        end
      }
      format.js {}
    end
  end

  # FOR MAIN HOME PAGE
  def indexmain
    respond_to do |format|
      format.html {
        @question = Question.new
        if params[:tag]
          @feed = Question.tagged_with(params[:tag]).paginate(:per_page => 4, :page => params[:page])
        else
          @feed=Question.last(10).reverse
          @latestfeed=Question.last(10).reverse
          @tftags=Question.tag_counts_on(:tags).order('count desc').limit(5)
          @trendingfeed=[]
          @tftags.each do |tag|
            @trendingfeed += Question.tagged_with(tag)
          end
        end
      }
      format.js {}
    end
  end
  # FOR ALL TAGS
  def tags_list

  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_question.html.erb
 <!-- ########################################################################################################## 

                                       PARTIAL FOR QUESTION CARDS
                                          
 ########################################################################################################### -->
<head>
  <style type="text/css">

    div.card.ques {
      font-family: 'Roboto', sans-serif;
      display: block;
      width: 90%;
      height:auto;
      margin: 3px auto 6px;
      background-color: #ffffff;
      border-radius: 2px;
      overflow-y: hidden;
      overflow-wrap: normal;
      overflow-x: hidden;
      transition-duration: 0.3s;
      transition-property: box-shadow;
      -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
      transform: translateZ(3);
      border: 1px solid #d1d1d1;
      border-radius: 6px;
    }

    div.card.ques:hover {
      box-shadow: 0 12px 12px rgba(0, 0, .6, .6);
    }
    div.card.ques div.card-title{
      padding: 16px;
    }

    div.card.ques div.card-title figure {
      width: 40px;
      height: 40px;
      margin: 0 16px 0 0;
      padding: 0;
      border-radius: 50%;
      float: left;
    }
    div.card.ques div.card-title div.text h1{
      font-size: 24px;
      font-weight: normal;
      line-height: 1;
      padding: 0;
      margin: 8px;
    }
    div.card.ques div.card-title div.text h2{
      color: #757575;
      font-size: 14px;
      font-weight: normal;
      line-height: 1;
      padding: 0;
      margin: 12px 0 0;
    }
    div.card.ques div.card-title div.text.small h1{
      margin-top: 1px;
      margin-left: 1px;
      font-size: 20px;
    }

    div.card.ques div.supporting_text h3{
      padding-left: 16px;
      font-size: 17px;
      margin-top: 0;
      margin-bottom: 0;
    }
    div.card.ques div.supporting_text p {
      font-size: 18px;
      line-height: 1.5;
      margin: 0;
      padding: 2px 5px 4px 13px;
    }
    div.card.ques div.row{
      padding: 1px;
      height: auto;
      margin-bottom: 0px;
    }

    div.card.ques div.card-action {
      position: relative;
      background-color: inherit;
      border-top: 1px solid rgba(160,160,160,0.2);
      padding: 4px 24px;
    }
    div.card.ques div.card-action div.right {
      float: right;
    }
    div.card.ques div.card-action a {
      color: #757575;
      /*height: 36px;*/
      margin: 0;
      margin-right: 0px;
      padding: 0px;
      background-color: #ffffff;
      border: none;
      font-size: 14px;
      text-transform: uppercase;
      border-radius: 2px;
    }

    div.card.ques div.supporting_text.text.small div.row div.card-action a i.material-icons{
      color:#949599;
      border-radius: 50%; 
    }
    div.card.ques div.supporting_text.text.small div.row div.card-action a i.material-icons:hover{
      color:#0091ea;
    }
    l div.card.ques div.supporting_text.text.small div.row div.card-action a{
      color:#949599;
      border-radius: 50%; 
    }
    div.card.ques div.supporting_text.text.small div.row div.card-action a:hover{
      color:#0091ea;
    }
    div.card.ques.hoverable div.supporting_text.text.small div.row div.card-action a i.btn , 
    div.card.ques div.supporting_text.text.small div.row div.card-action a.btn{
      color: #fff;
      background-color: #949599;
      border: none;
      border-radius: 20px;
      display: inline-block;
      height: 30px;
      line-height: 30px;
      padding: 0 1rem;
      text-transform: uppercase;
      vertical-align: middle;
    }
    div.card.ques.hoverable div.supporting_text.text.small div.row div.card-action a i.btn:hover,
    div.card.ques div.supporting_text.text.small div.row div.card-action a.btn:hover{
      color: #fff;
      background-color:#00b8d4 ;
      z-index: 8000;
    }
    .card .card-action a:not(.btn):not(.btn-large):not(.btn-large):not(.btn-floating){
      margin-right: 0px;
    }
    [elevation='1'] {
      box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
    }

    [elevation='2'] {
      box-shadow: 0 3px 6px rgba(0, 0, 0, 0.16), 0 3px 6px rgba(0, 0, 0, 0.23);
    }

    [elevation='3'] {
      box-shadow: 0 10px 20px rgba(0, 0, 0, 0.19), 0 6px 6px rgba(0, 0, 0, 0.23);
    }

    [elevation='4'] {
      box-shadow: 0 14px 28px rgba(0, 0, 0, 0.25), 0 10px 10px rgba(0, 0, 0, 0.22);
    }

    [elevation='5'] {
      box-shadow: 0 19px 38px rgba(0, 0, 0, 0.3), 0 15px 12px rgba(0, 0, 0, 0.22);
    }
  </style>
</head>
<div class="question">
  <div class="userDetail">
    <div class="card ques hoverable" elevation="2">
      <div class="card-title">
        <figure elevation="1">
          <%=avatar_for(question.user,size: 40)%>
        </figure>
        <div class="text small">
          <h1 style="font-family: 'Fresca', sans-serif;"><%= link_to question.user.name,user_path(question.user.id) %></h1>
          <h2><%= time_ago_in_words(question.created_at) unless question.created_at.blank? %> ago</h2>
        </div>

      </div>
      <div class="supporting_text text small">
        <h3 style=" font-family: 'Cantarell, sans-serif';font-size: 22px;font-weight: bold;" class="truncate" ><%= link_to question.content.truncate(200) ,question%></h3>
        <% if question.answers.first != nil %>
        <% ans = question.answers.first %>
        <p style="font-family: 'Josefin Slab', serif;" ><%= raw ans.content.truncate(400) %></p>
        <% end %>
        <p style=" font-family: 'Capriola, sans-serif';font-size: 14px;">Tags:  <%= raw question.tag_list.map { |t| link_to t , tag_path(t) }.join(', ') %></p>
        <div class="row">
          <div class="card-action">
            <%= link_to ('<i class="btn">Answer</i>').html_safe, question ,params[id: question.id] %>
            <% if current_user !=nil %>
            <% if question.follow_string(current_user.id,question.id)== true%>
            <%= link_to(('<span class="">Unfollow</span>').html_safe, question_follow_path(question), remote:true,method: :post,id: "follow_#{question.id}",:class =>"waves-effect waves-light btn") %>
            <%else%>
            <%= link_to(('<span class="">follow</span>').html_safe, question_follow_path(question), remote:true,method: :post,id: "follow_#{question.id}",:class =>"waves-effect waves-light btn") %>
            <%end%>
            <%end%>
            <div class="right">
              <% if current_user !=nil %>
              <% if question.like_string(current_user.id,question.id)== true%>
              <%= link_to ('<i class="material-icons right tooltipped" data-position="bottom" data-delay="50" data-tooltip="Like">favorite</i>').html_safe, question_like_path(question), remote:true,method: :post ,id: "like_#{question.id}" %>
              <%else%>
              <%= link_to ('<i class="material-icons right tooltipped" data-position="bottom" data-delay="50" data-tooltip="Like">favorite_border</i>').html_safe, question_like_path(question), remote:true,method: :post ,id: "like_#{question.id}" %>
              <%end%>
              <%end%>
              <% if current_user !=nil %>
              <%if can? :update,question%>
              <%= link_to ('<i class="material-icons right tooltipped" data-position="bottom" data-delay="50" data-tooltip="Edit">create</i>').html_safe, edit_question_path(question)%>
              <%end%>
              <%if can? :destroy,question%>
              <%= link_to ('<i class="material-icons right tooltipped" data-position="bottom" data-delay="50" data-tooltip="Delete">delete</i>').html_safe, question, method: :delete, data: {confirm: "Are you sure?"}%>
              <%end%>
              <%end%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $('.tooltipped').tooltip({delay: 50});
</script>

app/views/home/_user_list.html.erb
 <!-- ########################################################################################################## 

                                       PARTIAL FOR USERS CARDS 
                                          
 ########################################################################################################### -->
<% if user != current_user %>
 <div class="col l6 m6 s12">
  <div id="usercard2" class="card userfour usercol">
      <div class="header"></div>
      <div class="wrapper">
        <div class="image-wrapper"><%=avatar_for(user,size: 100)%></div>
        <h3 class="name"><%= link_to user.name,user_path(user.id) %></h3>
        <p style="margin: 8px 0px;text-align: center; padding: 0 15px;"><%= user.bio %></p>
    <div class="social usercf">
          <div class="userfour usercol">
            <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
          </div>
          <div class="userfour usercol">
            <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
          </div>
          <div class="userfour usercol">
            <a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
          </div>
        </div> 
        <div class="info usercf">
          <div class="userfour usercol"><span class="number"><%= user.followees(User).count %></span>Following</div>
          <div class="userfour usercol"><span class="number"><%= user.questions.count %></span>Questions</div>
          <div class="userfour usercol"><span class="number"><%= user.followers(User).count %></span>Followers</div>
        </div>
        <div class="center"> 
        <span class="btn"><% if user.follow_string(current_user.id,user.id)== true%>
      <%= link_to('Unfollow', user_follow_path(user), remote:true,method: :post,class: "follow1_#{user.id}") %>
      <%else%>
      <%= link_to('follow', user_follow_path(user), remote:true,method: :post,class: "follow1_#{user.id}") %>
      <%end%></span>
      </div>
      </div>
    </div>
 </div>
<% end %>

app/views/home/index.html.erb
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>HOME</title>
  <style media="screen">
    .apple_pagination {
      background: #f1f1f1;
      border: 1px solid #e5e5e5;
      text-align: center;
      padding: 1em;
      cursor: default;
    }

    .apple_pagination a, .apple_pagination span {
      padding: 0.2em 0.3em;
    }

    .apple_pagination .disabled {
      color: #aaaaaa;
    }

    .apple_pagination .current {
      font-style: normal;
      font-weight: bold;
      background-color: #bebebe;
      display: inline-block;
      width: 1.4em;
      height: 1.4em;
      line-height: 1.5;
      -moz-border-radius: 1em;
      -webkit-border-radius: 1em;
      border-radius: 1em;
      text-shadow: rgba(255, 255, 255, 0.8) 1px 1px 1px;
    }

    .apple_pagination a {
      text-decoration: none;
      color: black;
    }

    .apple_pagination a:hover, .apple_pagination a:focus {
      text-decoration: underline;
    }

    div#modal2.modal.modal-fixed-footer.open div.createQuestion div.modal-content span h4 {
      margin-bottom: 0;
    }

    div#modal2.modal.modal-fixed-footer.open div.createQuestion div.modal-footer div.actions.modal-action.modal-close.waves-effect.waves-green.cyan.btn-flat {
      padding: 0;
      border-radius: 25px;
    }

    div#modal2.modal.modal-fixed-footer.open div.createQuestion div.modal-footer div.actions.modal-action.modal-close.waves-effect.waves-green.cyan.btn-flat input#create_question_submit {
      padding-top: 10px;
    }
  </style>
</head>
<body>
 <!-- ##################################  MODALFOR ASKING NEW QUESTION  ########################################-->
 <div id="modal2" class="modal modal-fixed-footer">
  <div class="createQuestion">
    <%= form_for @question, remote: true do |task| %>
    <div class="modal-content">
      <span><h4 style="display: inline-block;">ASK QUESTION</h4>
        <button class="modal-action modal-close waves-effect waves-green transparent btn-flat right" style="display: inline-block;padding: 0;"><i class="material-icons">close</i></button>
      </span>
      <div class="input-field">
        <%= task.hidden_field :title, class: 'validate', id: 'title' %>
      </div>
      <div class="input-field">
        <%= task.text_area :content, class: 'validate materialize-textarea', id: 'content' %><br>
        <%= task.label :Question, for: 'content' %><br>
      </div>
      <div class="input-field">
        <%= task.label :tag_list, "Tags (separated by commas)" %>
        <%= task.text_field :tag_list %>
      </div>
    </div>
    <div class="modal-footer">
      <div class="actions modal-action modal-close waves-effect waves-green cyan btn-flat">
        <%= task.submit id: 'create_question_submit' %>
      </div>
    </div>
    <% end %>
    <% if @question.errors.any? %>
    <% @question.errors.full_messages.each do |message| %>
    <%= message %>
    <% end %>
    <% end %>
  </div>
</div>
<!-- ***********************************  MODALFOR ASKING NEW QUESTION ENDS  ***************************************  -->

<div id="questions">
  <a class="modal-trigger" href="#modal2">
    <div class=card class="z-depth-1" style="width: 93%; height: 60px;margin-bottom: 0; margin-top: 10px;margin-left: 25px; padding-left: 24px;padding-top: 0.5px; background: #ffffff;border: 2px solid #949599;">
      <a class="modal-trigger" href="#modal2" style="color: #949599; margin-bottom: 10px;"><h5>Ask Your Question</h5>
      </a>
    </div>
  </a>
  <div class="row">
    <% unless @trend.nil? %>
    <div class="chip" style="margin-top: 25px;margin-left: 50px;font-size: 30px;">
      <%= @trend.name %>
    </div>

    <% if @trend.follow_string(current_user.id, @trend.id)== true %>
    <%= link_to(('<i class="material-icons tagicon">check</i>').html_safe, trend_follow_path(@trend), remote: true, method: :post, class: "follow1_#{@trend.id}") %>
    <% else %>
    <%= link_to(('<i class="material-icons tagicon">add</i>').html_safe, trend_follow_path(@trend), remote: true, method: :post, class: "follow1_#{@trend.id}") %>
    <% end %>
    <% end %>

    <% if @users!=nil %>
    <% @users.each do |u| %>
    <%= render 'user_list', user: u %>
    <% end %>
    <% end %>

    <!-- ##################################  ALL SEARCHED QUESTION ########################################-->


    <% if @feed!=nil %>
    <% @feed.each do |question| %>
    <div class="col s12 m12 l12">
      <%= render 'question', question: question %>
    </div>
    <% end %>
    <%end%>

  </div>

  <!-- ##################################  PAGINATION ########################################-->

  <% if @feed!=nil %>
  <div class="apple_pagination">
    <div class="page_info">
      <%= page_entries_info @feed %>
    </div>
    <%= will_paginate @feed, :container => false %>
  </div>
  <%end%>

</div>

<script type="text/javascript">
  $(document).ready(function () {
        // the "href" attribute of the modal trigger must specify the modal ID that wants to be triggered
        $('#modal2').on('click', function () {
        });

        $('#modal2').modal({
            dismissible: true, // Modal can be dismissed by clicking outside of the modal
            opacity: 0, // Opacity of modal background
            inDuration: 300, // Transition in duration
            outDuration: 200, // Transition out duration
            startingTop: '4%', // Starting top style attribute
            endingTop: '10%', // Ending top style attribute
          });

        $('#modal2').modal('open');
        $('.trigger-modal').modal();
        $('#modal2').modal('close');
        $('input#title, textarea#content').characterCounter();
      });
    </script>
    <script type="text/javascript" charset="utf-8">
      <% if current_user!=nil %>
      $("#create_question_submit").click(function () {
        noty({
          text: 'You Successfully posted a new question',
          type: 'alert',

          progressBar: true
        });
      });
      <% else%>
      $("#create_question_submit").click(function () {
        noty({
          text: 'You must login or signup before raising a question!!',
          type: 'error',

          progressBar: true
        });
        $('#log_in_modal').click();

      });
      <% end %>
    </script>

  </body>
  <head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>HOME</title>
    <style media="screen">
      .apple_pagination {
        background: #f1f1f1;
        border: 1px solid #e5e5e5;
        text-align: center;
        padding: 1em;
        cursor: default;
      }

      .apple_pagination a, .apple_pagination span {
        padding: 0.2em 0.3em;
      }

      .apple_pagination .disabled {
        color: #aaaaaa;
      }

      .apple_pagination .current {
        font-style: normal;
        font-weight: bold;
        background-color: #bebebe;
        display: inline-block;
        width: 1.4em;
        height: 1.4em;
        line-height: 1.5;
        -moz-border-radius: 1em;
        -webkit-border-radius: 1em;
        border-radius: 1em;
        text-shadow: rgba(255, 255, 255, 0.8) 1px 1px 1px;
      }

      .apple_pagination a {
        text-decoration: none;
        color: black;
      }

      .apple_pagination a:hover, .apple_pagination a:focus {
        text-decoration: underline;
      }

      div#modal2.modal.modal-fixed-footer.open div.createQuestion div.modal-content span h4 {
        margin-bottom: 0;
      }

      div#modal2.modal.modal-fixed-footer.open div.createQuestion div.modal-footer div.actions.modal-action.modal-close.waves-effect.waves-green.cyan.btn-flat {
        padding: 0;
        border-radius: 25px;
      }

      div#modal2.modal.modal-fixed-footer.open div.createQuestion div.modal-footer div.actions.modal-action.modal-close.waves-effect.waves-green.cyan.btn-flat input#create_question_submit {
        padding-top: 10px;
      }
    </style>
  </head>
  <body>
   <!-- ##################################  MODALFOR ASKING NEW QUESTION  ########################################-->
   <div id="modal2" class="modal modal-fixed-footer">
    <div class="createQuestion">
      <%= form_for @question, remote: true do |task| %>
      <div class="modal-content">
        <span><h4 style="display: inline-block;">ASK QUESTION</h4>
          <button class="modal-action modal-close waves-effect waves-green transparent btn-flat right" style="display: inline-block;padding: 0;"><i class="material-icons">close</i></button>
        </span>
        <div class="input-field">
          <%= task.hidden_field :title, class: 'validate', id: 'title' %>
        </div>
        <div class="input-field">
          <%= task.text_area :content, class: 'validate materialize-textarea', id: 'content' %><br>
          <%= task.label :Question, for: 'content' %><br>
        </div>
        <div class="input-field">
          <%= task.label :tag_list, "Tags (separated by commas)" %>
          <%= task.text_field :tag_list %>
        </div>
      </div>
      <div class="modal-footer">
        <div class="actions modal-action modal-close waves-effect waves-green cyan btn-flat">
          <%= task.submit id: 'create_question_submit' %>
        </div>
      </div>
      <% end %>
      <% if @question.errors.any? %>
      <% @question.errors.full_messages.each do |message| %>
      <%= message %>
      <% end %>
      <% end %>
    </div>
  </div>
  <!-- ***********************************  MODALFOR ASKING NEW QUESTION ENDS  ***************************************  -->

  <div id="questions">
    <a class="modal-trigger" href="#modal2">
      <div class=card class="z-depth-1" style="width: 93%; height: 60px;margin-bottom: 0; margin-top: 10px;margin-left: 25px; padding-left: 24px;padding-top: 0.5px; background: #ffffff;border: 2px solid #949599;">
        <a class="modal-trigger" href="#modal2" style="color: #949599; margin-bottom: 10px;"><h5>Ask Your Question</h5>
        </a>
      </div>
    </a>
    <div class="row">
      <% unless @trend.nil? %>
      <div class="chip" style="margin-top: 25px;margin-left: 50px;font-size: 30px;">
        <%= @trend.name %>
      </div>

      <% if @trend.follow_string(current_user.id, @trend.id)== true %>
      <%= link_to(('<i class="material-icons tagicon">check</i>').html_safe, trend_follow_path(@trend), remote: true, method: :post, class: "follow1_#{@trend.id}") %>
      <% else %>
      <%= link_to(('<i class="material-icons tagicon">add</i>').html_safe, trend_follow_path(@trend), remote: true, method: :post, class: "follow1_#{@trend.id}") %>
      <% end %>
      <% end %>

      <% if @users!=nil %>
      <% @users.each do |u| %>
      <%= render 'user_list', user: u %>
      <% end %>
      <% end %>

      <!-- ##################################  ALL SEARCHED QUESTION ########################################-->


      <% if @feed!=nil %>
      <% @feed.each do |question| %>
      <div class="col s12 m12 l12">
        <%= render 'question', question: question %>
      </div>
      <% end %>
      <%end%>

    </div>

    <!-- ##################################  PAGINATION ########################################-->

    <% if @feed!=nil %>
    <div class="apple_pagination">
      <div class="page_info">
        <%= page_entries_info @feed %>
      </div>
      <%= will_paginate @feed, :container => false %>
    </div>
    <%end%>

  </div>

  <script type="text/javascript">
    $(document).ready(function () {
        // the "href" attribute of the modal trigger must specify the modal ID that wants to be triggered
        $('#modal2').on('click', function () {
        });

        $('#modal2').modal({
            dismissible: true, // Modal can be dismissed by clicking outside of the modal
            opacity: 0, // Opacity of modal background
            inDuration: 300, // Transition in duration
            outDuration: 200, // Transition out duration
            startingTop: '4%', // Starting top style attribute
            endingTop: '10%', // Ending top style attribute
          });

        $('#modal2').modal('open');
        $('.trigger-modal').modal();
        $('#modal2').modal('close');
        $('input#title, textarea#content').characterCounter();
      });
    </script>
    <script type="text/javascript" charset="utf-8">
      <% if current_user!=nil %>
      $("#create_question_submit").click(function () {
        noty({
          text: 'You Successfully posted a new question',
          type: 'alert',

          progressBar: true
        });
      });
      <% else%>
      $("#create_question_submit").click(function () {
        noty({
          text: 'You must login or signup before raising a question!!',
          type: 'error',

          progressBar: true
        });
        $('#log_in_modal').click();

      });
      <% end %>
    </script>

  </body>

app/views/home/index.js.erb
<% @feed.each do |question| %>
$('#questions').append("<%= escape_javascript (render 'home/question', question: question) %>");
<%end%>

app/views/home/indexmain.js.erb
<% @trendingfeed.each do |question| %>
$('#questions').append("<%= escape_javascript (render 'home/question', question: question) %>");
console.log("trending rendered");
<% end %>
<% @latestfeed.each do |question| %>
console.log("latest rendered");
$('#questions').append("<%= escape_javascript (render 'home/question', question: question) %>");
<% end %>

app/views/home/tags_list.html.erb
<style type="text/css">
	
	.card.small{
		display: none;
	}
</style>
<div class="card" style="padding: 5px;">
	
<div id="tag_cloud">
    
        <% tag_cloud Question.tag_counts, %w[sml med lar] do |tag, css_class| %>
           
   <div class="chip">
    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
    <i class="close material-icons">close</i>
  </div>
    
  <% end %>
    
</div>

</div>

app/views/home/users_list.js.erb
<% @users.each do |u| %>
$('#users').append("<%= escape_javascript (render 'home/user_list', user: u) %>");
<% end %>