config/routes.rb
Rails.application.routes.draw do

  resources 'surveys'
  resources 'attempts'
  match '(errors)/:status', to: 'errors#error_404', constraints: {status: /\d{3}/}, via: :all
  get '/passwordverification',to: 'surveys#quiz_confirm_password'
  post 'verifyPass',to: 'surveys#quiz_verfication'
  mount Ckeditor::Engine => '/ckeditor'
  resources :notes
  get 'tags/:tag', to: 'home#index', as: :tag
 get '/result/:id' => 'surveys#result'
  resources :questions

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :comments
  resources :answers
  resources :questions

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  get '/likenotification',to: 'notification#likeindex'
  get 'home/index'
  get '/sear',to: 'questions#index'
  devise_for :users, :controllers => { sessions: "sessions", registrations: "registrations",:omniauth_callbacks => "omniauth_callbacks" }
  devise_scope :user do
    authenticated :user do
      root 'home#indexmain', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  resources :users,only: [:show,:edit,:update]
  get '/users_list'=>'home#users_list'
  get '/tags_list'=>'home#tags_list'
 
  resources :questions do
    post 'like',   to: 'socializations#like'
    post 'follow', to: 'socializations#followQuestion'
  end

  resources :answers do
    post 'like',   to: 'socializations#likeAnswer'
  end
  resources :trends do
    post 'follow', to: 'socializations#followTrend'
  end
  resources :users do
    post 'follow', to: 'socializations#followUser'
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  has_many :likes
  has_many :comments ,dependent: :destroy
  validates :content ,presence: true,length:{maximum:20000,
    too_long: "%{count} characters is the maximum allowed" }
  acts_as_likeable
  def commentfeed answer_id
    Comment.where(answer_id: answer_id).order(created_at: :desc)
  end

  def liked_by user_id, answer_id
    Like.where(likeable_type: "Answer",liker_id: user_id,likeable_id: answer_id).length > 0
  end
  def like_string user_id,answer_id
    if (liked_by user_id,answer_id)
      return true
    else
      return false
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :create, :update, :destroy]
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  

# TO SHOW AN ANSWER
def show
  respond_to do |format|
    format.html {
      @answer=Answer.find(params[:id])
      @comment = Comment.new(answer_id: params[@answer.id])
      @commentfeed=@answer.commentfeed @answer.id

    }
    format.js {}
  end
end

# FOR NEW ANSWER
def new
  @answer = Answer.new(question_id: params[:question_id])
end

# TO EDIT AN ANSWER
def edit
end

# TO CREATE AN ANSWER
def create
  @question = Question.find(params[:question_id])
  @answer = @question.answers.create(answer_params)
  @answer.user_id = current_user.id
  respond_to do |format|
    if @answer.save
        # TO GENERATE A MAIL WHEN NEW ANSWER IS CREATED
        Resque.enqueue(AnswerMailer,@answer.id,current_user.id)
        Notification.create(recipient: @question.user,actor: current_user,action: "Posted",notifiable: @answer,url: @question_path)
        (@question.users.uniq).each do |user|
          if user==current_user
            next
          end
          Notification.create(recipient: user,actor: current_user,action: "Posted An Answer",notifiable: @answer.question)
        end
        format.html {redirect_to 'home/questions/', notice: 'Answer was successfully created.'}
        format.js {}
        @comment = Comment.new(answer_id: params[@answer.id])
        @commentfeed=@answer.commentfeed @answer.id
        format.json {render :show, status: :created, location: @answer}
      else
        format.html {render 'home/index'}
        format.json {render json: @answer.errors, status: :unprocessable_entity}
      end
    end
  end

# TO UPDATE AN ANSWER
def update
  respond_to do |format|
    if @answer.update(answer_params)
      format.html {redirect_to '/questions/<% question_id %>', notice: 'Answer was successfully updated.'}
      format.json {render :show, status: :ok, location: @answer}
    else
      format.html {render :edit}
      format.json {render json: @answer.errors, status: :unprocessable_entity}
    end
  end
end

# TO DELETE AN ANSWER
def destroy
  @answer.destroy
  respond_to do |format|
    format.html {redirect_to '/', notice: 'Answer was successfully destroyed.'}
    format.json {head :no_content}
  end
end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_answer
    @answer = Answer.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def answer_params
    params.require(:answer).permit(:content, :question_id, :user_id)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_comment.html.erb
<style type="text/css">
  *{font-family:calibri;}

  .message .avatar{
    border-radius:100px;
    width:80px;
    height:80px;
    float:left;
  }
  .message{
    position:relative;
    clear:both;
    width:100%;
  }
  .message .avatar{
    margin-top:5px;
  }
  .message p{
    float:left;
    font-family:calibri;
    color:#333;
    width: 85%;
    margin:0;
    margin-left:20px;
    margin-top:5px;
    padding:10px;
    background-color:#fafafa;
    border:1px solid #eee;
    border-radius:5px;
    margin-bottom:10px;
    word-spacing:3px;
    line-height:22px;
  }
  .message p em.info{
    display:block;
    text-align:right;
    margin-top:10px;
    font-size:12px;
    font-weight:bold;
    color:666px;
  }
  .message p strong{
    display:block;
    color:#428bca;
    border-bottom:1px solid #ddd;
    margin-bottom:10px;
  }
  .message p strong em{
    font-weight:normal;
    color:#333;
    font-size:10pt;
  }
  .message .triangle{
    display:block;
    position:absolute;
    left:85px;
    top:25px;
    width: 0;
    height: 0;
    border-style: solid;
    border-width: 10px 15px 10px 0;
    border-color: transparent #eeeeee transparent transparent;
  }

  @media screen and (max-width: 1140px) {
    #global{width:100%;}
    .message{float:none;margin:auto;}
    .messages{float:none;margin:auto;}

  }
  @media screen and (max-width: 620px) {
    
    body{margin-right:60px;}
    .message .avatar,.inverse .avatar,.message .triangle,.inverse .triangle{display:none;}

  }
</style>


<div class="comment">
  <div class="userDetail">
    <div class="messages">
      <div class="message">
        <div class="triangle"></div>
        <div class="avatar"><%=avatar_for(comment.user,size: 40)%></div>
        
        <p><strong><%= link_to comment.user.name,user_path(comment.user.id) %>,<em><%= time_ago_in_words(comment.created_at) unless comment.created_at.blank? %> ago</em></strong>
         <%= comment.content %>
         <br>
         <%if can? :destroy,comment%>
         <%= link_to ('<i class="material-icons tooltipped right" data-position="bottom" data-delay="50" data-tooltip="Delete">delete</i>').html_safe, comment, method: :delete, data: {confirm: "Are you sure?"}%>
         <% end %>
       </p>
     </div>
     <br>
   </div>
 </div>
</div>

app/views/answers/_form.html.erb
 <!-- ########################################################################################################## 

                                       FORM FOR EDIT ANSWER
                                          
 ########################################################################################################### -->

<%= form_for(@answer) do |f| %>
<% if @answer.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

  <ul>
    <% @answer.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="card z-depth-4 center" style="border: 1px solid #d1d1d1;
border-radius: 10px;">
<div class="green darken-3 z-depth-4" style="padding-bottom:20px;">
  <br>
  <span class="card-title white-text">Edit answer</span>
  <br>
</div>
<form>
  <div class="col s12" style="padding:0;">
    <div class="input-field">
     <%= f.cktext_area :content, rows: 10,id: 'ckeditid' %>
     <label for="answer_content" data-error="wrong" data-success="right">Content</label>
   </div>

   <br>
 </div>

 <div class="action" style="padding:40px;">
  <%= f.submit "Save" , class:"waves-effect waves-light btn green darken-3"%>
  <%= link_to 'Back', @answer.question, class:"waves-effect waves-light btn green darken-3 left" %>
</div>
</form>
</div>
<% end %>

<script type="text/javascript">
  $('.tooltipped').tooltip({delay: 50});
</script>

app/views/answers/create.js.erb
$('#answers').prepend("<%= escape_javascript (render 'questions/answer', answer: @answer) %>");
$('#answer_content').val("");

app/views/answers/edit.html.erb
<!-- <%if can? :update,@answer%>
<h1>Editing Answer</h1> -->

<%= render 'form' %>

<!-- <%= link_to 'Show', @answer %> |
 <%= link_to 'Back', questions_path %>
 <%else%>
 <%= render file: 'public/404', status: 404, formats: [:html] %>
 <%end%>  -->

app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<head>
  <style type="text/css">
    /* Imports */
    @import url(https://fonts.googleapis.com/css?family=Lato:400,300);
    @import url(https://fonts.googleapis.com/css?family=Lato:400,300);
    #cardques.card{

     background: #4DA0B0;  /* fallback for old browsers */
     background: -webkit-linear-gradient(to left, #D39D38, #4DA0B0);  /* Chrome 10-25, Safari 5.1-6 */
     background: linear-gradient(to left, #D39D38, #4DA0B0); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
     margin-bottom: 10px;
     transition-duration: 0.3s;
     transition-property: box-shadow;
     -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
     transform: translateZ(3);
   }

   div#cardques.card:hover {
    box-shadow: 0 12px 12px rgba(0, 0, .6, .6);
  }
  #cardques .card-title{
    padding:1rem;
    border-bottom: 0px;
  }

  #cardques .card-title .fakeimage {
    width: 50px;
    height: 50px;
    float: left;
    border-radius: 100%;
  }
  #cardques .card-title h2,  .card-title .wrap > p {
    margin-bottom: 10px;
    font-family: Lato, sans-serif;
    font-size: 1.2em;
    color: #222;
  }
  #cardques .card-title p {
    margin-right: 10px;
    margin-left: 10px;
    font-family: Lato, sans-serif;
    font-size: 0.9em;
    color: #aaa;
    float: left;
  }
  #cardques .card-title #quesuserdetail{
    margin-left: 65px;
    margin-top: 12px;

  }
  #cardques .card-title #quesuserdetail h4{
    font-family: 'Fresca', sans-serif;
    font-size: 1.5rem;
    line-height: 91%;
    margin: 0;
  }
  #cardques .card-title #quesuserdetail p{
    font-size: 16px;
    line-height: 91%;
    margin: 0;
  }
  div#quescontent{
    padding-top: 0px;
    padding-bottom: 2px;
  }
  div#quescontent h5{
    margin-top: 0;
    margin-bottom: 3px;
    color: #696a6e;
  }
  div#quescontent p{
    color: #6f6f6f;
  }
  .card{
    transition-duration: 0.3s;
    transition-property: box-shadow;
    -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
    transform: translateZ(3);
  }
  div.card:hover {
    box-shadow: 0 12px 12px rgba(0, 0, .6, .6);
  }
  .card-title{
    padding:1rem;
    border-bottom: 0px;
    font-size: 19px;
    font-weight: 300;
  }
  .card-title .fakeimage {
    width: 50px;
    height: 50px;
    float: left;
    border-radius: 100%;
  }
  .card-title h2,  .card-title .wrap > p {
    margin-bottom: 10px;
    font-family: Lato, sans-serif;
    font-size: 1.2em;
    color: #222;
  }
  .card-title p {
    color: #696a6e;
    margin-right: 10px;
    margin-left: 10px;
    font-family: Lato, sans-serif;
    font-size: 0.9em;
    color: #aaa;
    float: left;
  }
  .card-title h5#head{
    color: #696a6e;
    font-weight: bold;
    font-size: 1.4rem;
    line-height: 110%;
    margin: 0 0 0 0;
  }
  .card-title p#head{
    color: #696a6e;
    font-size: 0.8rem;
    font-weight: bold;
    margin-top: 0px;
    margin-bottom: 0px;
  }
  .card-title p i {
    color: #696a6e;
    margin-right: 0;
    margin-left: 0;
    font-family: Lato, sans-serif;
    font-size: 0.7em;
    float: left;
    margin-top: 0px;
    margin-bottom: 0px;
  }
  html body div#mithu.container div.row div.col.s12.m12.l7 div#answers div.row div.col.s12.m12.l12 div.answer div.userDetail div.card div.card-content.grey-text.text-darken-3{
    padding: 24px;
    padding-top: 0px;
    padding-bottom: 24px;
    border-radius: 0 0 2px 2px;
    padding-bottom: 2px;
    padding-top: 0px;
  }
  html body div#mithu.container div.row div.col.s12.m12.l7 div#answers div.row div.col.s12.m12.l12 div.answer div.userDetail div.card div.card-title.row{
    margin-bottom:0px;
  }
  html body div#mithu.container div.row div.col.s12.m12.l7 div#answers div.row div.col.s12.m12.l12 div.answer div.userDetail div.card div.card-title.row div.left.details{
    margin-left: 10px;

  }
  html body div#mithu.container div.row div.col.s12.m12.l7 div#answers div.row div.col.s12.m12.l12 div.answer div.userDetail div.card div.card-content.grey-text.text-darken-3 div.row a i.material-icons.right{
    color:#949599;
  }
  html body div#mithu.container div.row div.col.s12.m12.l7 div#answers div.row div.col.s12.m12.l12 div.answer div.userDetail div.card div.card-content.grey-text.text-darken-3 div.row a i.material-icons.right:hover{
    color:#0091ea;
  }
  html body div#mithu.container div.row div.col.s12.m12.l7 div#answers div#modal1.modal.modal-fixed-footer.open div.modal-footer{
    height: 122px;
  }
  .modal .modal-footer .btn-flat{
    background-color: #81d4fa;
  }
  html body div#mithu.container div.row div.col.s12.m12.l7 div#cardques.card.hoverable div#quescontent.card-content.grey-text div.row a.waves-effect.waves-light.btn.follow.right{
    color: #fff;
    background-color: #949599;
    border: none;
    border-radius: 20px;
    display: inline-block;
    height: 30px;
    line-height: 30px;
    padding: 0 1rem;
    text-transform: uppercase;
    vertical-align: middle;
  }
  html body div#mithu.container div.row div.col.s12.m12.l7 div#cardques.card.hoverable div#quescontent.card-content.grey-text div.row a.waves-effect.waves-light.btn.follow.right:hover{
   color: #fff;
   background-color:#00b8d4 ;
   z-index: 8000;
 }
</style>

</head>
<div id="cardques" class="card hoverable">
  <div class="card-title">
    <div class="fakeimage">
      <div class="circle responsive-img valign profile-image"><%=avatar_for(@answer.question.user,size: 40)%></div>
    </div>
    <div id="quesuserdetail">
      <h4><%= link_to @answer.question.user.name,user_path(@answer.question.user.id) %></h4>
      <p ><%= time_ago_in_words(@answer.question.created_at) unless @answer.question.created_at.blank? %> ago</p>
    </div>
  </div>
  <br>
  <div id="quescontent" class="card-content grey-text">
    <h5 style=" font-family: 'Cantarell, sans-serif';font-size: 22px;font-weight: bold;"><%= @answer.question.title %></h5>
    <p style="font-family: 'Josefin Slab', serif; font-weight:bold;"><%= @answer.question.content %></p>
    <div class="row">
      <%if can? :update,@answer.question%>
      <%= link_to ('<i class="material-icons right">create</i>').html_safe, edit_question_path(@answer.question)%>
      <% end %>
      <%if can? :destroy,@answer.question%>
      <%= link_to ('<i class="material-icons right">delete</i>').html_safe, @answer.question, method: :delete, data: {confirm: "Are you sure?"}%>
      <% end %>
      <% if @answer.question.follow_string(current_user.id,@answer.question.id)== true%>
      <%= link_to(('<span class="">Unfollow</span>').html_safe, question_follow_path(@answer.question), remote:true,method: :post,id: "follow_#{@answer.question.id}",:class =>"waves-effect waves-light btn follow right") %>
      <%else%>
      <%= link_to(('<span class="">follow</span>').html_safe, question_follow_path(@answer.question), remote:true,method: :post,id: "follow_#{@answer.question.id}",:class =>"waves-effect waves-light btn follow right") %>
      <%end%>
    </div>
  </div>
</div>


<div class="answer">
  <div class="userDetail">
    <div class="card hoverable">
      <div class="card-title row" style="padding-bottom: 0px;">
        <div class="fakeimage left" style="margin-left: 10px;">
          <div class="picture"><%=avatar_for(@answer.user,size: 40)%></div>
        </div>
        <div class="left details">
          <h5 id="head"><%= @answer.user.name %></h5>
          <p id="head" style="font-weight: 700"><%= time_ago_in_words(@answer.created_at) unless @answer.created_at.blank? %> ago</p>
          <br>
        </div>
      </div>
      <div class="card-content grey-text text-darken-3" style="padding-top: 0px; padding-bottom: 5px;">
        <p style="font-family: Lato"><%= raw @answer.content %></p>
        <br>
        <div class="row" style="padding-bottom: 0px;">
          <%= link_to ('<i class="material-icons tooltipped right" data-position="bottom" data-delay="50" data-tooltip="Comment">forum</i>').html_safe, @answer ,params[id: @answer.id]%></button>
          <%if can? :update,@answer%>
          <%= link_to ('<i class="material-icons tooltipped right" data-position="bottom" data-delay="50" data-tooltip="Edit Answer">create</i>').html_safe,edit_answer_path(@answer) %>
          <% end %>
          <%if can? :destroy,@answer%>
          <%= link_to ('<i class="material-icons tooltipped right" data-position="bottom" data-delay="50" data-tooltip="Delete">delete</i>').html_safe, @answer, method: :delete, data: {confirm: "Are you sure?"}%>
          <% end %>
          <a class="waves-effect waves-light grey btn tooltipped modal-trigger" data-position="bottom" data-delay="50" data-tooltip="Comment" href="#modal1">Comment</a>
          <% if @answer.like_string(current_user.id,@answer.id)== true%>
          <%= link_to ('<i class="material-icons right" >favorite</i>').html_safe, answer_like_path(@answer), remote:true,method: :post ,id: "like_#{@answer.id}" %>
          <%else%>
          <%= link_to ('<i class="material-icons right" >favorite_border</i>').html_safe, answer_like_path(@answer), remote:true,method: :post ,id: "like_#{@answer.id}" %>
          <%end%>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Modal Structure -->
<div id="modal1" class="modal modal-fixed-footer">
  <div class="modal-content">
    <div id="comments">
      <% @commentfeed.each do |comment| %>
      <%= render 'comment' , comment: comment %>
      <% end %>
    </div>
  </div>
  <div class="modal-footer">
    <div class="createComment">
      <%= form_for @comment, :url => comments_path(answer_id:@answer.id), remote: true do |task|%>
      <%= task.label :comment %><br>
      <%= task.text_area :content %><br>
      <div class="actions">
        <%= task.submit id: 'create_comment_submit', class:"modal-action modal-close waves-effect waves-green btn-flat"%>
      </div>
      <% end %>
      <% if @comment.errors.any? %>
      <% @comment.errors.full_messages.each do |message| %>
      <%= message %>
      <% end %>
      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
        // the "href" attribute of the modal trigger must specify the modal ID that wants to be triggered
        $('#modal1').modal();
        $('#modal1').on('click', function () {
        });
        $('#modal1').modal({
  dismissible: true, // Modal can be dismissed by clicking outside of the modal
      opacity: 0, // Opacity of modal background
      inDuration: 300, // Transition in duration
      outDuration: 200, // Transition out duration
      startingTop: '4%', // Starting top style attribute
      endingTop: '10%', // Ending top style attribute
    });
        $('#modal1').modal('open');
        $('.trigger-modal').modal();
        $('#modal1').modal('close');
        $('.tooltipped').tooltip({delay: 50});
      });
    </script>

app/views/answers/show.js.erb
<% @commentfeed.each do |comment| %>
$('#comments').append("<%= escape_javascript (render 'answers/comment', comment: comment,answer_id: @answer.id) %>");
<% end %>