config/routes.rb
Rails.application.routes.draw do

  resources 'surveys'
  resources 'attempts'
  match '(errors)/:status', to: 'errors#error_404', constraints: {status: /\d{3}/}, via: :all
  get '/passwordverification',to: 'surveys#quiz_confirm_password'
  post 'verifyPass',to: 'surveys#quiz_verfication'
  mount Ckeditor::Engine => '/ckeditor'
  resources :notes
  get 'tags/:tag', to: 'home#index', as: :tag
 get '/result/:id' => 'surveys#result'
  resources :questions

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :comments
  resources :answers
  resources :questions

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  get '/likenotification',to: 'notification#likeindex'
  get 'home/index'
  get '/sear',to: 'questions#index'
  devise_for :users, :controllers => { sessions: "sessions", registrations: "registrations",:omniauth_callbacks => "omniauth_callbacks" }
  devise_scope :user do
    authenticated :user do
      root 'home#indexmain', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  resources :users,only: [:show,:edit,:update]
  get '/users_list'=>'home#users_list'
  get '/tags_list'=>'home#tags_list'
 
  resources :questions do
    post 'like',   to: 'socializations#like'
    post 'follow', to: 'socializations#followQuestion'
  end

  resources :answers do
    post 'like',   to: 'socializations#likeAnswer'
  end
  resources :trends do
    post 'follow', to: 'socializations#followTrend'
  end
  resources :users do
    post 'follow', to: 'socializations#followUser'
  end

end

app/views/layouts/_modal.html.erb
 <!-- ########################################################################################################## 

                                          MODAL FOR SIGNUP / SIGNIN 
                                          
 ########################################################################################################### -->

 <style media="screen">
  #modal7 .modal-content{
    padding-top: 130px;
    padding: 2px;
  }
  #modal7 .row2{
    padding-top: 0px;
  }
  #modal7 .row1{
    padding-bottom: 3px;
    padding-left: 60px;
    padding-right: 60px;
  }
  #modal7 .row1 input{
    color: #333;
    transition: none;
  }
  #modal7 .card-panel1{
    background: rgba(40, 57, 101, .9);
    height: 37px;
    padding-top: 0;
    padding-bottom: 0;
    padding-left: 0;
    padding-right: 0;
    margin-left: 15px;
    margin-right: 15px;
    border-radius: 5px;
  }
  #modal7 #tabsign a.active{
    background: rgba(40, 57, 101, .9);
    margin-left: -2px;
    margin-right: -2px;
    border-radius: 10px;
    color: white;
  }
  #modal7 #tabsign.tabs .indicator{
    display: none;
  }
  #modal7 #tabsign a{
    color:rgba(40, 57, 101, .9);
  }
  #modal7 .btt{
    background: rgba(40, 57, 101, .9);
  }
  div#modal7.modal.open div.modal-content div.row2 div#test-swipe-2.active form#new_user.new_user div.row1 div.input-field.col.s12 input{
    margin: 0;
    margin-left: 45px;
  }
  div#modal7.modal.open{
    transform: none;
    overflow-y: hidden;
  }
</style>
<div class="row2">
  <ul id="tabsign" class="tabs tabs-fixed-width">
    <li class="tab col s6 "><a href="#test-swipe-1"> Sign In</a></li>
    <li class="tab col s6 "><a class="active" href="#test-swipe-2">Sign Up</a></li>
  </ul>
  <br>
  <div id="test-swipe-1">
    <div class="card-panel1 z-depth-4">
     <div class="center-align">
      <%- if devise_mapping.omniauthable? %>
      <%- resource_class.omniauth_providers.each do |provider| %>
      <%= link_to ('<i class="fa fa-facebook-square"></i>').html_safe, omniauth_authorize_path(resource_name, :facebook),class:"waves-effect waves-light btn transparent"%><br />
      <% end -%>
      <% end -%>
    </div>
  </div>
  <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <form class="col s12">
    <div class="row1">
      <div class="input-field col s12">
        <i class="material-icons prefix">email</i>
        <%= f.email_field :email, autofocus: false, class:"validate"%>
        <label for="user_email", class="">Email</label>
      </div>
      <div class="input-field col s12">
        <i class="material-icons prefix">lock_outline</i>
        <%= f.password_field :password, autocomplete: "off", class:"validate" %>
        <label for="user_password">Password</label>
      </div>
      
      <div class="">
        <% if devise_mapping.rememberable? -%>
        <%= f.check_box :remember_me %>
        <label for="user_remember_me">Remember me</label>
        <!-- <%= f.label :remember_me %> -->
        <% end %></p>
        <% if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
        <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
        <% end -%>
        <%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
        <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
        <% end -%>
      </div>
      <br>
      <button class="btn waves-effect waves-light right btt white-text" type="submit" name="action">
        <i class="material-icons right">send</i>SUBMIT</button>
        <br>
      </div>
    </form>
    <%end%>
  </div>
  <div id="test-swipe-2">
    <div class="card-panel1 z-depth-4">
     <div class="center-align">
      <%- if devise_mapping.omniauthable? %>
      <%- resource_class.omniauth_providers.each do |provider| %>
      <%= link_to ('<i class="fa fa-facebook-square"></i>').html_safe, omniauth_authorize_path(resource_name, :facebook),class:"waves-effect waves-light btn transparent"%><br />
      <% end -%>
      <% end -%>
    </div>
  </div>
  <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>
  <form class="col s12">
    <div class="row1">
      <div class="input-field col s12">
        <i class="material-icons prefix">account_circle</i>
        <%=f.text_field :name, autofocus: false,class:"validate"%>
        <label for="user_name">Username</label>
      </div>
      <div class="input-field col s12">
        <i class="material-icons prefix">email</i>
        <%= f.email_field :email, autofocus: false, class:"validate"%>
        <label for="user_email", class="">Email</label>
      </div>

      <div class="input-field col s12">
        <i class="material-icons prefix">lock_outline</i>
        <% if @minimum_password_length %>
        <em>(<%= @minimum_password_length %> characters minimum)</em>
        <% end %>
        <%= f.password_field :password, autocomplete: "off", class:"validate"%>
        <label for="user_password">Password</label>
      </div>
      <div class="input-field col s12">
        <i class="material-icons prefix">lock_outline</i>
        <%= f.password_field :password_confirmation, autocomplete: "off", class:"validate" %>
        <label for="user_password">Confirm Password</label>
      </div>
      <br>
      <button class="btn waves-effect waves-light right btt white-text" type="submit" name="action">
        <i class="material-icons right">send</i>SUBMIT</button>
        <br>
      </div>
    </form>
    <%end%>
  </div>
</div>

app/views/layouts/_modaladdnote.html.erb
 <!-- ########################################################################################################## 

                                          MODAL FOR ADDING NEW NOTE 
                                          
 ########################################################################################################### -->

<%= form_for(@note) do |f| %>
<% if @note.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

  <ul>
    <% @note.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="modal-content">
 <div class="field">
  <%= f.label :title %><br>
  <%= f.text_field :title %>
  <%= f.label :content %><br>
  <%= f.text_area :content, class:'validate materialize-textarea'%> 
</div>
</div>
<div class="modal-footer">
  <a class="modal-action modal-close waves-effect waves-green btn-flat ">  <%= f.submit %></a>
</div> 
<% end %>

app/views/layouts/_modalshownote.html.erb
 <!-- ########################################################################################################## 

                                          MODAL FOR SHOWING NOTE
                                          
 ########################################################################################################### -->

 <%if Note.where(:user_id => current_user.id).length>0%>

        <p>  <%= Note.where(:user_id => current_user.id).last.content %></p><%end%>
        <br>
        <hr><%if Note.where(:user_id => current_user.id).length>=2%>
        <br>
        <p><%= Note.where(:user_id => current_user.id)[-2].content %><%end%>
        </p>

app/views/layouts/_modaltag.html.erb
 <!-- ########################################################################################################## 

                                          MODAL FOR SHOWING ALL TAGS
                                          
 ########################################################################################################### -->
<% if user_signed_in? %>
<span>
      <button class="modal-action modal-close waves-effect waves-green transparent btn-flat right" style="display: inline-block;"><i class="material-icons">close</i></button>
    </span>
<div id="tag_cloud">
    
        <% tag_cloud Question.tag_counts, %w[sml med lar] do |tag, css_class| %>
           
   <div class="chip">
    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
     <% @trend=Trend.where(name: tag.name).first %>
            <% if @trend != nil %>

            <% if @trend.follow_string(current_user.id,@trend.id)== true%>
            <%= link_to(('<i class="material-icons tagicon">check</i>').html_safe, trend_follow_path(@trend), remote:true,method: :post,class: "follow1_#{@trend.id}") %>
            <%else%>
            <%= link_to(('<i class="material-icons tagicon">add</i>').html_safe, trend_follow_path(@trend), remote:true,method: :post,class: "follow1_#{@trend.id}") %>
            <%end%>
            <%end%>

  </div>
    
  <% end %>
    
</div>
  <% end %>
    

app/views/layouts/_sideques.html.erb
 <!-- ########################################################################################################## 

                                         PARTIAL FOR QUESTION CARD ON RIGHT
                                          
 ########################################################################################################### --> 
<style type="text/css">
	
	.card.quesrelate{
		width:270px;
		padding-bottom: 10px;
	}
	.card.quesrelate hr{
		color: #dddfe7;

	}
	div.card.quesrelate div.card-content{
		max-height: 210px;
		overflow-y: auto;
	}
</style>

<% if @questagfeed != nil && @questagfeed.length >0 %>

<div class="card quesrelate"> 
	<div class="card-title center" style="color:#696a6e;font-size: 28px;font-weight: 800;font-family: Fresca,sans-serif;"> 
		Related Questions
	</div>
	<div class="card-content">
		<% @questagfeed.each do |ques| %>
		<%= link_to ques.title, ques %>
		<hr>
		<% end %>
	</div>
</div>
<% end %>



<% if @tre!= nil && @trendtagusers!= nil%>
<% if @trendtagusers.length >=0 %>
<div class="card quesrelate"> 
	<div class="card-title center" style="color:#696a6e;font-size: 28px;font-weight: 800;font-family: Fresca,sans-serif;"> 
		Trend Followers
	</div>
	<div class="card-content">
		<% @trendtagusers.each do |trenduser| %>
		
		<%= link_to trenduser.name, trenduser %>
		<hr>
		<% end %>
	</div>
</div>
<% end %>
<% end %>

app/views/layouts/layout_one.html.erb
<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel='stylesheet prefetch' href='http://cdnjs.cloudflare.com/ajax/libs/animate.css/3.2.3/animate.min.css'>
<link href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.css" rel="stylesheet"/>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js" type="text/javascript" charset="utf-8">
</script>
<script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.15.2/moment.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>

 <!-- ########################################################################################################## 

                                         MAIN LAYOUT PAGE FOR QUIZZES
                                          
 ########################################################################################################### -->

<div class="container">
<br>
<br>
<br>
  <div class="flash">
    <% flash.each do |name, msg| %>
        <%if correct_flash_name(name)=='info' || correct_flash_name(name)=='alert'%>
        <div class="alert alert-<%= correct_flash_name(name) %>" role="alert">
          <%= msg %>
        </div>
            <%end%>
    <% end %>
  </div>
 
 
</div>
<%= yield %>

 <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
<script src='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js'></script>